### ISSUE TITLE
add a downloadable version of the video with license

### ISSUE THREAD

**Issue by jcolomb** [jennybc/how-to-name-files#1]
Hello,

thanks for sharing, fantastic summary of best practices!

I would be nice to add the video file here, we cannot download YouTube videos, as well as adding a license to it, so we can reuse it without thinking about it.
(Alternatively use zenodo or figshare for this.)

**Comment by jennybc** [comment]
I had already thought about the lack of license. I'm more familiar with licensing code or, even, data. Do you happen to know of a great example of how something similar has been shared that works well for you? Meaning a video, licence, downloadable (or even any one of those).

**Comment by jcolomb** [comment]
There may be issues with the content you did not create, probably works under fair use in the USA/UK (but there is no fair use rule in the EU).

Otherwise, videos can be licensed with CC licenses, even on YouTube.
To make it downloadable, either put it here or on Zenodo/figshare.

example: https://doi.org/10.6084/m9.figshare.7053797.v7
